config/routes.rb
Public::Application.routes.draw do

  resources :propertymeasures
  resources :installed_measure_types
  resources :record_lookups
  
  devise_for :users, :controllers => {:registrations => "newusers", :destroy => "newusers"}
  devise_scope :user do
  authenticated :user do
       root :to =>'dashboard#index'
	end
    unauthenticated :user do
	root :to => 'devise/sessions#new'
   end
  end

  resources :recordings
  resources :properties

  resources :newusers
  resources :users

  get "dashboard/property_report"

  get "dashboard/prism_report_electric"
  get "dashboard/prism_report_gas"
  post '/uploads/upload' => 'uploads#upload'
  post '/uploads/uploadGas' => 'uploads#uploadGas'
  resources :dashboard

  
  
  post '/stagings/insert' => 'stagings#insert'
  post '/stagings/destroyAll' => 'stagings#destroyAll'
  resources :stagings do
	collection do
    		put :update_attribute_on_the_spot
    		get :get_attribute_on_the_spot
  	end
  end

  get 'analysis', to: 'analysis#index'
  get 'analysis/null_accounts'
  get 'analysis/dominion_ready_accounts'
  get 'analysis/dominion_ready_accounts_prism'
  get 'analysis/cvillegas_ready_accounts'
  get 'analysis/cvillegas_ready_accounts_prism'
  get 'analysis/washingtongas_ready_accounts'
  get 'analysis/washingtongas_ready_accounts_prism'

  get 'filtering', to: 'filtering#index'
  match '/filtering_reset' => 'filtering#reset', :as=>'reset'
  get "filtering/prism_report_electric", :defaults=> {format: 'csv'}
  get "filtering/prism_report_gas", :defaults=> {format: 'csv'}

  get 'requests', to: 'requests#index'
  get 'requests/dominion_request_accounts'
  get 'requests/cvillegas_request_accounts'
  get 'requests/washingtongas_request_accounts'

  get 'uploads/stagings', to: 'stagings#index'
  resources :uploads do
	member do
	    get :process
	end
  end

  root :to => "dashboard#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    #autocomplete :property, :owner_name
    #USER, PASSWORD = 'dhh', 'secret'
    #before_filter :authentication_check   #, :except => :index
    include DashboardHelper
    include PropertiesHelper
    
    
    def index
        @variables = Property.find(:all).map { |x| x.owner_name+" - "+x.street_address }#&:owner_name)
        
        #@addresses = Property.find(:all, :select=>'street_address').map(&:street_address)
        #@variables = @names+@addresses #Property.select([:owner_name, :street_address]).map {|e| {owner_name: e.owner_name, street_address: e.street_address} }
        #@property = Property.find_by_owner_name(params[:owner])
        #@property = Property.search(params[:owner])
        #city, state, zipcode
        #File.open("variables.json","w+") do |f|
        #    f.write(@variables.to_json)
        #end
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @property }
        end
        
    end
    
    def property_report
        
        @utilitytypes = UtilityType.all.to_a
        @companynames= RecordLookup.uniq.pluck(:company_name)
        @recording = Recording.new
        @record_lookup = RecordLookup.new
        @propmeasure = Propertymeasure.new
        @num_electric_recordings = 0
        @num_gas_recordings = 0
        @current_measures = nil;
        
        if params[:customer_unique_id]
            @property = Property.find_by_customer_unique_id(params[:customer_unique_id])
            elsif params[:owner]
            @property = Property.search(params[:owner])
            @property = @property.shift
        end
        
        if (@property)
        
            @current_measures = Propertymeasure.where("property_id = ?", @property.id).to_a
            @testoutdate = @property.finish_date
            if(@testoutdate)
                @startdate = start_date(@testoutdate);
                @enddate = end_date(@testoutdate);
                @months = gap_months(@startdate)
            end
            
            @electric_record_lookups = RecordLookup.where("property_id = ? AND utility_type_id = ?", @property.id, 1).to_a #ID and Electric
            
            if (!@electric_record_lookups.blank?)
                if(@testoutdate)
                    @electric_recordings = get_records(@electric_record_lookups, @startdate, @enddate)
                    
                    if(@electric_recordings)
                        if(@electric_recordings.length > 0)
                            @electric_gap_data = get_data(@electric_recordings, @startdate)
                
                            
                            @num_electric_recordings = get_data_count(@electric_recordings, @startdate)
                            else
                            @electric_recordings = nil;
                        end
                    end
                end
            end
            
            @gas_record_lookups = RecordLookup.where("property_id = ? AND utility_type_id = ?", @property.id, 2).to_a
            
            if (!@gas_record_lookups.blank?)
                
                if(@testoutdate)
                    @gas_recordings = get_records(@gas_record_lookups, @startdate, @enddate)
                    if(@gas_recordings)
                        if(@gas_recordings.length > 0)
                            @gas_gap_data = get_data(@gas_recordings, @startdate)
                            
                            
                            @num_gas_recordings = get_data_count(@gas_recordings, @startdate)
                            else
                            @gas_recordings = nil;
                        end
                    end
                end
            end
            
            if(!@testoutdate)
                flash.now[:alert] = "This property does not contain a listed test out date!"
            end
        
        else
        flash.now[:alert] = "A property with that owner name does not exist. Try again."
        redirect_to :action => 'index'
    end
end


def prism_report_electric
    if params[:owner]
        @property = Property.search(params[:owner])
        @property = @property.shift
    end
    if @property
        sql = "select properties.customer_unique_id, MONTH(read_date),DAY(read_date),YEAR(recordings.read_date),recordings.consumption,utility_types.units,
        IF(recordings.read_date>properties.finish_date,'POST','PRE')
        ,'Carbon' as 'Group','R' as 'Flag'
        from properties
        left join record_lookups on properties.id = record_lookups.property_id
        left join recordings on record_lookups.acct_num = recordings.acctnum
        left join utility_types on utility_types.id = recordings.utility_type_id
        where customer_unique_id = '" + @property.customer_unique_id + "' and record_lookups.utility_type_id=1
        ORDER BY ABS(UNIX_TIMESTAMP(recordings.read_date) - UNIX_TIMESTAMP(properties.finish_date))
        ASC LIMIT 22";
        @records_array = ActiveRecord::Base.connection.execute(sql)
        
        header = ["Building ID", "Month", "Day", "Year","Consumption","Units","P-Field","Group","Flag"]
        fields = 9
        respond_to do |format|
            format.html
            format.csv { send_data csv_export(header, @records_array, fields) }
        end
        else
        flash[:alert] = "A property with that owner name does not exist. Try again."
        redirect_to :action => 'index'
    end
end

def prism_report_gas
    if params[:owner]
        @property = Property.search(params[:owner])
        @property = @property.shift
    end
    if @property
        sql = "select properties.customer_unique_id, MONTH(read_date),DAY(read_date),YEAR(recordings.read_date),recordings.consumption,utility_types.units,
        IF(recordings.read_date>properties.finish_date,'POST','PRE')
        ,'Carbon' as 'Group','R' as 'Flag'
        from properties
        left join record_lookups on properties.id = record_lookups.property_id
        left join recordings on record_lookups.acct_num = recordings.acctnum
        left join utility_types on utility_types.id = recordings.utility_type_id
        where customer_unique_id = '" << @property.customer_unique_id << "' and record_lookups.utility_type_id=2
        ORDER BY ABS(UNIX_TIMESTAMP(recordings.read_date) - UNIX_TIMESTAMP(properties.finish_date))
        ASC LIMIT 22";
        @records_array = ActiveRecord::Base.connection.execute(sql)
        
        header = ["Building ID", "Month", "Day", "Year","Consumption","Units","P-Field","Group","Flag"]
        fields = 9
        respond_to do |format|
            format.html
            format.csv { send_data csv_export(header, @records_array, fields) }
        end
        else
        flash[:alert] = "A property with that owner name does not exist. Try again."
        redirect_to :action => 'index'
    end
end

def csv_export(header, data, fields)
    CSV.generate do |csv|
        csv << header #["Owner Name", "Customer Unique ID", "Company Name", "Account Number"]
        recordline = Array.new(fields)
        data.each do |record|
            puts record
            fields.times{ |i| recordline[i] = record[i]}
            csv << recordline #[record[0], record[2], record[3], record[4]]
            recordline = Array.new(fields)
        end
    end
end

def update
    
    respond_to do |format|
        if @property.update_attributes(params[:property])
            format.html { redirect_to(@property, :notice => 'Property was successfully updated.') }
            format.xml  { head :ok }
            else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
        end
    end
end

private
def authentication_check
    authenticate_or_request_with_http_basic do |user, password|
        user == USER && password == PASSWORD
    end
end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
require 'iconv'
require 'roo'

	# change excel files to csv
	def xls2csv
	    print "start conversion....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	    Dir["/leap/public/uploads/*.xlsx"].each do |file|  
	      file_path = "#{file}"
	      file_basename = File.basename(file, ".xlsx")
	      xlsx = Roo::Excelx.new(file_path)
	      $i = xlsx.sheets.length - 1
	      while $i >= 0 do
		xlsx.default_sheet = xlsx.sheets[$i]
		xlsx.to_csv("/leap/public/uploads/#{file_basename}#{$i}.csv")
		$i -=1	
	      end
	      FileUtils.remove(file)
	      print "Converted file #{file} \n"
	    end
	end
end

app/views/dashboard/_current_measures.html.erb
<% if (!@current_measures.blank?) %>
	<table class="table">
	  <tr> <th align="center" colspan="4"> Installed Measures </th> </tr>
	  <tr>
	    <th>Type</th>
	    <th>Comment</th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @current_measures.each do |propertymeasure| %>
	  <tr>
	    <td><%= InstalledMeasureType.find(propertymeasure.installed_measure_type_id).installed_measures %></td>
	    <td><%= propertymeasure.comment %></td>
	    <td><%= link_to 'Destroy', propertymeasure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
	</table>
<% else %>
	<p> No current measures associated with this property. </p>
<%end %>

app/views/dashboard/index.html.erb
<%= stylesheet_link_tag "dashboard_style" %>
<div class="container theme-showcase">
	<div id="content" class="bs-docs-header">
		<div class="container marketing">
			<br>
			<div class="row">
				<div class="col-md-2">
					<%= image_tag "logo.png", class: "img-responsive" %>
				</div>
				<div class="form-inline" role= "form">
					
					<h1>Data Management and Visualization System</h1>
					<%= form_tag dashboard_property_report_path, #class: "form-control",
					 :method => "get" do %>
					<%= label_tag(:owner,"", class: "lead") %>
					<div id ="bloodhound1">
					<%= text_field_tag :owner, params[:owner], class: "typeahead form-control", size: 90, placeholder: "Search Properties" %>
					<button id= "search" type="submit" class="btn btn-primary">Search</button> 
					<% end %>
					</div>
		    			</p>
				</div>
			</div>
		</div>
	</div>
</div>
	
<script> 
var variables = new Bloodhound({
	datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
	queryTokenizer: Bloodhound.tokenizers.whitespace,
	limit: 8,
//	local: $.map(variables, function(variable) { return { value: variable }; })
 prefetch: {
	// url points to a json file that contains an array of country names, see
	// https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
	url: 'properties.json',
	// the json file contains an array of strings, but the Bloodhound
	// suggestion engine expects JavaScript objects so this converts all of
	// those strings
	filter: function(list) {
		return $.map(list, function(variable) { return { value: variable }; });
		}
	}
});

variables.initialize();

//here's my hacky fix bloodhound1
$('#bloodhound1 .typeahead').typeahead({
	hint: true,
	highlight: true,
	minLength: 1
	},
	{
	name: 'variables',
	displayKey: 'value',
	source: variables.ttAdapter()
});
</script>

	<div class="container marketing" > 
		<div class="row">
			<div class="col-lg-4">
				<h2>Upload</h2>
				<p>Upload housing, utility, and customer data by searching for the CSV file you would like to add to the system and uploading it.  This page also shows you the file name, time of upload, and status of all files the system has processed.  The most recent files appear at the top of the list. </p>
				<p>
					<%= button_to "View", uploads_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Analyze</h2>
				<p>View the properties that have enough data to be analyzed.  Search based on Dominion Virginia Power, Charlottesville Gas, Washington Gas, and Null Accounts.  Results will show all properties with the selected conditions.  The owner name for each property can be clicked on, and all information associated with that property will be displayed.  Results can be exported to a CSV file in a PRISM ready format.</p>
				<p>
					<%= button_to "View", analysis_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Measures</h2>
				<p>This page displays the complete list of possible installed measures.  Items can be added, deleted, or edited in this list.  Installed measures can also be associated with specific properties by entering the correct property id and measure.  A comments field is also available for entering information such as contractor data.</p>
				<p>
					<%= button_to "View", installed_measure_types_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<h2>Filter</h2>
				<p>Complete advanced searches here.  This allows the filtering of data based on utility type, installed measures, and the TO date range.</p>
				<p>
					<%= button_to "View", filtering_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Properties</h2>
				<p>Add a new property to the system here by entering property information such as customer name, address, and TO date.  The complete list of all LEAP properties is displayed here.  Each name in the properties list is clickable and will redirect to the entire data-set available for that specific property.</p>
				<p>
					<%= button_to "View", properties_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Request Data</h2>
				<p>Select to generate reports for missing data based on utility type.  The report can either be generated in HTML form or as a CSV in a PRISM ready format. </p>
				<p>
					<%= button_to "View", requests_path, :method => "get", type: 'button', class: 'btn btn-default' %>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<h2>Help</h2>
				<p>This system was created by the University of Virginia's Service Learning Practicum in the Computer Science Department.  Jon Proffitt has the user manual and contact information of the developers.</p>
			</div>
		</div>
	</div>
	<br>
	<hr class="divider">
	<p class="text-right">
      		© SLP LEAP 2014
    	</p>
</div>	

app/views/dashboard/null_account_export.html.erb
<h1>Missing Account Info</h1>

<table border="1">
  <tr>
    <th>Owner Name</th>
    <th>Customer Unique ID</th>
    <th>Company Name</th>
    <th>Account Number</th>
  </tr>

<% @records_array.each do |record| %>
  <tr>
    <td><%= record[0] %></td>
    <td><%= record[2] %></td>
    <td><%= record[3] %></td>
    <td><%= record[4] %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Back', root_path %>

app/views/dashboard/prism_report_gas.html.erb
<h1>PRISM Report - Electric</h1>
<table class="table table-striped" border="1">
  <tr>
    <th>Building ID</th>
    <th>Month</th>
    <th>Day</th>
    <th>Year</th>
    <th>Consumption</th>
    <th>Units</th>
    <th>P-Field</th>
    <th>Group</th>
    <th>Flag</th>
  </tr>

<% @records_array.each do |record| %>
  <tr>
    <td><%= record[0] %></td>
    <td><%= record[1] %></td>
    <td><%= record[2] %></td>
    <td><%= record[3] %></td>
    <td><%= record[4] %></td>
    <td><%= record[5] %></td>
    <td><%= record[6] %></td>
    <td><%= record[7] %></td>
    <td><%= record[8] %></td>
  </tr>
<% end %>

<br />
<%= link_to 'Back', dashboard_index_path %>

app/views/dashboard/property_report.html.erb
<%= stylesheet_link_tag "report_style" %>

<% title "Customer #{@property.customer_unique_id}" %>
<div class="container">
<div class="row">
	<div class="col-lg-6">
		<h3><%= "Report for Customer #{@property.customer_unique_id}" %></h3>
	</div>
	
	<div class="col-lg-3">
		<a href="<%= dashboard_prism_report_electric_path + ".csv?owner=" + @property.owner_name%>" class="btn pull-left btn-primary btn-sm" style="color:white; margin-top:22px; margin-bottom:10px;">PRISM Format - Electric Data Export</a>
	</div>
	<div class="col-lg-3">
		<a href="<%= dashboard_prism_report_gas_path + ".csv?owner=" + @property.owner_name%>" class="btn pull-right btn-primary btn-sm" style="color:white; margin-top:22px; margin-bottom:10px;">PRISM Format - Gas Data Export</a>
	</div>
</div>



<div class="row">
	<div class="col-lg-6">
		<h4><strong><%= " " + @property.owner_name %></strong></h4>
		<h4><%= @property.street_address %></h4>
		<h4><%= "#{@property.city}, #{@property.state} #{@property.zipcode}"%></h4>
		<% if (!@electric_record_lookups.blank?) %>
			<% for i in 0..(@electric_record_lookups.count - 1) %>
				<h5><%= "Account (" + @electric_record_lookups[i].company_name + "): " + @electric_record_lookups[i].acct_num %></h5>
			<% end %>
			
		<% end %>

		<% if (!@gas_record_lookups.blank?) %>
			<% for i in 0..(@gas_record_lookups.count - 1 ) %>
				<h5><%= "Account (" + @gas_record_lookups[i].company_name + "): " + @gas_record_lookups[i].acct_num %></h5>
			<% end %>
		<% end %>
		<% if (@property.finish_date) %>
			<h5><strong> Test Out Date:  </strong> <%= " " + @testoutdate.strftime("%B %e, %Y")%></h5>
		<%else%>
			<%= render 'form_to' %>
		<% end %>
		<%= button_to "Edit Property", edit_property_path(@property), type: 'button', :method => "get", class: 'btn btn-primary btn-sm' %>

	
	</div>
	<hr>

	<div class="col-lg-4">
		<a href="javascript:toggleDiv('accountform');"> <button class = "btn pull-left btn-primary btn-sm"> Add New Account </button></a>
		<br/>
		<br/>
		<div id ="accountform">
			<%= render 'form_account' %>
		</div>
	</div>
	<div class="col-lg-2">
		<a href="javascript:toggleDiv('rawdata');"> <button class = "btn pull-right btn-primary btn-sm"> Display Raw Data </button></a>
	</div>
</div>

<script type="text/javascript">
	function toggleDiv(divId) {
		$("#"+divId).toggle();
	}
</script>
<hr>
<div id="rawdata">
	<% if (@electric_recordings && @gas_recordings) %>

		<h3> Raw Data </h3>

		<table class="table table-bordered">
			<tr>
				<th colspan="3"> Electricity</th>
				<th colspan="3"> Gas</th>
			</tr>
			<tr>
				<th> Read Date </th>
				<th> Consumption </th>
				<th> Days in Month </th>
				<th> Read Date </th>
				<th> Consumption </th>
				<th> Days in Month </th>
			</tr>
			<% for i in 0..[@electric_recordings.count-1, @gas_recordings.count-1].max %>
				<tr>
					<%if(@electric_recordings[i])%>
						<td> <%= @electric_recordings[i].read_date %> </td>
						<td> <%= @electric_recordings[i].consumption %> </td>
						<td> <%= @electric_recordings[i].days_in_month %> </td>
					<%else%>
						<td></td>
						<td></td>
						<td></td>
					<%end%>
					<%if(@gas_recordings[i])%>
						<td> <%= @gas_recordings[i].read_date %> </td>
						<td> <%= @gas_recordings[i].consumption %> </td>
						<td> <%= @gas_recordings[i].days_in_month %> </td>
					<%else%>
						<td></td>
						<td></td>
						<td></td>
					<%end%>
				</tr>
			<% end %>
		</table>
	<% end %>

	<% if (@electric_recordings && !@gas_recordings) %>

		<h4> Raw Data </h4>

		<table class="table table-bordered">
			<tr>
				<th colspan="3"> Electricity</th>
			</tr>
			<tr>
				<th> Read Date </th>
				<th> Consumption </th>
				<th> Days in Month </th>
			</tr>
			<% for i in 0..@electric_recordings.count-1 %>
				<tr>
					<td> <%= @electric_recordings[i].read_date %> </td>
					<td> <%= @electric_recordings[i].consumption %> </td>
					<td> <%= @electric_recordings[i].days_in_month %> </td>
				</tr>
			<% end %>
		</table>
	<% end %>

	<% if (!(@electric_recordings) && @gas_recordings) %>

		<h4> Raw Data </h4>

		<table class="table table-bordered">
			<tr>
				<th colspan="3"> Gas</th>
			</tr>
			<tr>
				<th> Read Date </th>
				<th> Consumption </th>
				<th> Days in Month </th>
			</tr>
			<% for i in 0..@gas_recordings.count-1 %>
				<tr>
					<td> <%= @gas_recordings[i].read_date %> </td>
					<td> <%= @gas_recordings[i].consumption %> </td>
					<td> <%= @gas_recordings[i].days_in_month %> </td>
				</tr>
			<% end %>
		</table>
	<% end %>
</div>


<% if (@electric_recordings) %>
	<h4> Gaps Report - Electricity </h4>

	<table class="table table-bordered">
	  <tr>
	    <th colspan="12" > 12 Months Pre-Testout</th>
	  </tr>
	  <tr >
	    <% for i in 0..((@months.count-1)/2) %>
	    <td><%= @months[i].strftime("%b") + " " + @months[i].strftime("%Y")%></td>
	    <%end%>
	  </tr>
	  <tr>
	  		
	  		<% for i in 0..11 %>
	  			<% if(@electric_gap_data[i] != 0 && @electric_gap_data[i] != "---") %>
	  				<td bgcolor="11F215"> <%= @electric_gap_data[i] %> </td>
		  		<% elsif (@electric_gap_data[i] == 0) %>
					<td bgcolor="FFD700"> <%= @electric_gap_data[i] %> </td>
	  			<%else %>
	  				<td bgcolor="F24E4E"> <%= @electric_gap_data[i] %> </td>	
               	<% end %>
            <% end %>
		    
	  </tr>
	  <tr >
	    <th colspan="12" > 12 Months Post-Testout</th>
	  </tr>
	  <tr>
	    <% for i in ((@months.count)/2)..(@months.count-1) %>
	    <td><%= @months[i].strftime("%b") + " " + @months[i].strftime("%Y")%></td>
	    <%end%>
	  </tr>
	  <tr>
	  		<% for i in 12..23 %>
	  			<% if(@electric_gap_data[i] != 0 && @electric_gap_data[i] != "---") %>
	  				<td bgcolor="11F215"> <%= @electric_gap_data[i] %> </td>
		  		<% elsif (@electric_gap_data[i] == 0) %>
					<td bgcolor="FFD700"> <%= @electric_gap_data[i] %> </td>
	  			<%else %>
	  				<td bgcolor="F24E4E"> <%= @electric_gap_data[i] %> </td>	
               	<% end %>
            <% end %>
		    
	  </tr>
	</table>
<% end %>

<% if (@gas_recordings) %>
	
	<h4> Gaps Report - Gas </h4>

	<table class="table table-bordered">
	  <tr>
	    <th colspan="12" > 12 Months Pre-Testout</th>
	  </tr>
	  <tr >
	    <% for i in 0..((@months.count-1)/2) %>
	    <td><%= @months[i].strftime("%b") + " " + @months[i].strftime("%Y")%></td>
	    <%end%>
	  </tr>
	  <tr>
	  		
	  		<% for i in 0..11 %>
	  			<% if(@gas_gap_data[i] != 0 && @gas_gap_data[i] != "---" ) %>
	  				<td bgcolor="11F215"> <%= @gas_gap_data[i] %> </td>
		  		<% elsif (@gas_gap_data[i] == 0) %>
					<td bgcolor="FFD700"> <%= @gas_gap_data[i] %> </td>
	  			<%else%>
	  				<td bgcolor="F24E4E"> <%= @gas_gap_data[i] %> </td>	
               	<% end %>
            <% end %>
		    
	  </tr>
	  <tr >
	    <th colspan="12" > 12 Months Post-Testout</th>
	  </tr>
	  <tr>
	    <% for i in ((@months.count)/2)..(@months.count-1) %>
	    <td><%= @months[i].strftime("%b") + " " + @months[i].strftime("%Y")%></td>
	    <%end%>
	  </tr>
	  <tr>
	  		<% for i in 12..23 %>
	  			<% if(@gas_gap_data[i] != 0 && @gas_gap_data[i] != "---") %>
	  				<td bgcolor="11F215"> <%= @gas_gap_data[i] %> </td>
		  		<% elsif (@gas_gap_data[i] == 0) %>
					<td bgcolor="FFD700"> <%= @gas_gap_data[i] %> </td>
	  			<% else %>
	  				<td bgcolor="F24E4E"> <%= @gas_gap_data[i] %> </td>	
               	<% end %>
            <% end %>
		    
	  </tr>
	</table>
<% end %>	

<hr>

<div class="row">
	<div class="col-lg-4">
		<%= render 'form_recording' %>
	</div>
	
	<div class="col-lg-4">
		<%= render 'form_measure' %>
	</div>
	<div class="col-lg-4">
		<%= render 'current_measures' %>
	</div>
</div>
</div>

app/views/dashboard/utility_request_cvillegas_report.html.erb
<h1>Utility Requests for Charlottesville Gas</h1>

<table class="table table-striped" border="1">
  <tr>
    <th>Owner Name</th>
    <th>Address</th>
    <th>Account Number</th>
    <th>Number of Acceptable Meter Readings</th>
  </tr>

<% @records_array.each do |record| %>
  <tr>
    <td><%= link_to record[0], url_for(:controller => "dashboard", :action => "property_report", :owner => record[0]) %></td>
    <td><%= record[1] %></td>
    <td><%= record[2] %></td>
    <td><%= record[3] %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Back', dashboard_index_path %>
~                                               

app/views/dashboard/utility_request_dominion_report.html.erb
<h1>Utility Requests for Dominion Virginia Power</h1>

<table class="table table-striped" border="1">
  <tr>
    <th>Owner Name</th>
    <th>Address</th>
    <th>Account Number</th>
    <th>Number of Acceptable Meter Readings</th>
  </tr>

<% @records_array.each do |record| %>
  <tr>
    <td><%= link_to record[0], url_for(:controller => "dashboard", :action => "property_report", :owner => record[0]) %></td>
    <td><%= record[1] %></td>
    <td><%= record[2] %></td>
    <td><%= record[3] %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Back', dashboard_index_path %>
~                                                                                                                                                                                                   
~                                                       