config/routes.rb
Public::Application.routes.draw do

  resources :propertymeasures
  resources :installed_measure_types
  resources :record_lookups
  
  devise_for :users, :controllers => {:registrations => "newusers", :destroy => "newusers"}
  devise_scope :user do
  authenticated :user do
       root :to =>'dashboard#index'
	end
    unauthenticated :user do
	root :to => 'devise/sessions#new'
   end
  end

  resources :recordings
  resources :properties

  resources :newusers
  resources :users

  get "dashboard/property_report"

  get "dashboard/prism_report_electric"
  get "dashboard/prism_report_gas"
  post '/uploads/upload' => 'uploads#upload'
  post '/uploads/uploadGas' => 'uploads#uploadGas'
  resources :dashboard

  
  
  post '/stagings/insert' => 'stagings#insert'
  post '/stagings/destroyAll' => 'stagings#destroyAll'
  resources :stagings do
	collection do
    		put :update_attribute_on_the_spot
    		get :get_attribute_on_the_spot
  	end
  end

  get 'analysis', to: 'analysis#index'
  get 'analysis/null_accounts'
  get 'analysis/dominion_ready_accounts'
  get 'analysis/dominion_ready_accounts_prism'
  get 'analysis/cvillegas_ready_accounts'
  get 'analysis/cvillegas_ready_accounts_prism'
  get 'analysis/washingtongas_ready_accounts'
  get 'analysis/washingtongas_ready_accounts_prism'

  get 'filtering', to: 'filtering#index'
  match '/filtering_reset' => 'filtering#reset', :as=>'reset'
  get "filtering/prism_report_electric", :defaults=> {format: 'csv'}
  get "filtering/prism_report_gas", :defaults=> {format: 'csv'}

  get 'requests', to: 'requests#index'
  get 'requests/dominion_request_accounts'
  get 'requests/cvillegas_request_accounts'
  get 'requests/washingtongas_request_accounts'

  get 'uploads/stagings', to: 'stagings#index'
  resources :uploads do
	member do
	    get :process
	end
  end

  root :to => "dashboard#index"

end

app/models/recording.rb
class Recording < ActiveRecord::Base
  belongs_to :utility_type
  attr_accessible :acctnum, :consumption, :days_in_month, :read_date, :utility_type_id
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  # GET /recordings
  # GET /recordings.json
  
  helper_method :sort_column, :sort_direction
  
  def index
    @recordings = Recording.paginate(:page => params[:page]).order(sort_column + ' ' + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recordings }
      format.csv {render csv: @recordings}
    end
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/new
  # GET /recordings/new.json
  def new
    @recording = Recording.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/1/edit
  def edit
    @recording = Recording.find(params[:id])
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
          format.html { redirect_to dashboard_property_report_path(:commit => "Search", :owner => params[:recording][:owner]), notice: 'Recording was successfully created.' }
        format.json { render json: @recording, status: :created, location: @recording }
      else
        format.html { render action: "new" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recordings/1
  # PUT /recordings/1.json
  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url }
      format.json { head :no_content }
    end
  end
  
  def sort_column
      Recording.column_names.include?(params[:sort]) ? params[:sort] : "read_date"
  end
  
  def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
  
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :acctnum %><br />
    <%= f.text_field :acctnum %>
  </div>
  <div class="field">
    <%= f.label :consumption %><br />
    <%= f.text_field :consumption %>
  </div>
  <div class="field">
    <%= f.label :days_in_month %><br />
    <%= f.number_field :days_in_month %>
  </div>
  <div class="field">
    <%= f.label :read_date %><br />
    <%= f.date_select :read_date %>
  </div>
  <div class="field">
    <%= f.label :utility_type_id %><br />
    <%= f.text_field :utility_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<div class = "container">
<h1>All Recordings</h1>

<table class="table table-striped">
  <tr>
    <th><%= sortable "acctnum" %></th>
    <th><%= sortable "consumption" %></th>
    <th><%= sortable "days_in_month" %></th>
    <th><%= sortable "read_date" %></th>
    <th><%= sortable "utility_type" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recordings.each do |recording| %>
  <tr>
    <td><%= recording.acctnum %></td>
    <td><%= recording.consumption %></td>
    <td><%= recording.days_in_month %></td>
    <td><%= recording.read_date %></td>
    <td><%= recording.utility_type_id %></td>
    <td><%= link_to 'Show', recording %></td>
    <td><%= link_to 'Edit', edit_recording_path(recording) %></td>
    <td><%= link_to 'Destroy', recording, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

<%= will_paginate @recordings, renderer: BootstrapPagination::Rails %>

</table>

<%= will_paginate @recordings, renderer: BootstrapPagination::Rails %>


<br />

<%= link_to 'New Recording', new_recording_path %>
</div>

app/views/recordings/new.html.erb
<h1>New recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Acctnum:</b>
  <%= @recording.acctnum %>
</p>

<p>
  <b>Consumption:</b>
  <%= @recording.consumption %>
</p>

<p>
  <b>Days in month:</b>
  <%= @recording.days_in_month %>
</p>

<p>
  <b>Read date:</b>
  <%= @recording.read_date %>
</p>

<p>
  <b>Utility type:</b>
  <%= @recording.utility_type_id %>
</p>


<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>