config/routes.rb
Public::Application.routes.draw do

  resources :propertymeasures
  resources :installed_measure_types
  resources :record_lookups
  
  devise_for :users, :controllers => {:registrations => "newusers", :destroy => "newusers"}
  devise_scope :user do
  authenticated :user do
       root :to =>'dashboard#index'
	end
    unauthenticated :user do
	root :to => 'devise/sessions#new'
   end
  end

  resources :recordings
  resources :properties

  resources :newusers
  resources :users

  get "dashboard/property_report"

  get "dashboard/prism_report_electric"
  get "dashboard/prism_report_gas"
  post '/uploads/upload' => 'uploads#upload'
  post '/uploads/uploadGas' => 'uploads#uploadGas'
  resources :dashboard

  
  
  post '/stagings/insert' => 'stagings#insert'
  post '/stagings/destroyAll' => 'stagings#destroyAll'
  resources :stagings do
	collection do
    		put :update_attribute_on_the_spot
    		get :get_attribute_on_the_spot
  	end
  end

  get 'analysis', to: 'analysis#index'
  get 'analysis/null_accounts'
  get 'analysis/dominion_ready_accounts'
  get 'analysis/dominion_ready_accounts_prism'
  get 'analysis/cvillegas_ready_accounts'
  get 'analysis/cvillegas_ready_accounts_prism'
  get 'analysis/washingtongas_ready_accounts'
  get 'analysis/washingtongas_ready_accounts_prism'

  get 'filtering', to: 'filtering#index'
  match '/filtering_reset' => 'filtering#reset', :as=>'reset'
  get "filtering/prism_report_electric", :defaults=> {format: 'csv'}
  get "filtering/prism_report_gas", :defaults=> {format: 'csv'}

  get 'requests', to: 'requests#index'
  get 'requests/dominion_request_accounts'
  get 'requests/cvillegas_request_accounts'
  get 'requests/washingtongas_request_accounts'

  get 'uploads/stagings', to: 'stagings#index'
  resources :uploads do
	member do
	    get :process
	end
  end

  root :to => "dashboard#index"

end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController

  def index
  end

  #Gets all the null accounts from the Report module, NullAccount class
  def null_accounts
    @n_accounts = Report::NullAccount.paginate(:page => params[:page])
    header = ["Owner Name", "Customer Unique ID", "Company Name", "Account Number"]
    column_names = Report::NullAccount.column_names
    respond_to do |format|
      format.js
      format.csv { send_data csv_export(header, Report::NullAccount.all, column_names) }
      ajax_respond format, :section_id => "null_accounts"
    end
  end

  #Gets all the ready to analyze Dominion accounts from the Report module, DominionReadyAccount class, paginated
  def dominion_ready_accounts
    @accounts = Report::DominionReadyAccount.paginate(:page => params[:page])
    header = ["Owner Name", "Account Number", "Meter Readings"]
    column_names = Report::DominionReadyAccount.column_names
    respond_to do |format|
      format.js
      format.csv { send_data csv_export(header, Report::DominionReadyAccount.all, column_names) }
      ajax_respond format, :section_id => "dominion_ready_accounts"
    end
  end

  #Gets all the ready to analyze Dominion accounts from the Report module, DominionReadyAccount class, PRISM formatted
  def dominion_ready_accounts_prism
    customers = Report::DominionReadyAccount.pluck(:customer_unique_id)
    @records_array = prism_report(customers, "DOMINION")
    header = ["Building ID", "Month", "Day", "Year", "Consumption", "Units", "P-Field", "Group", "Flag"]
    fields = 9 
    respond_to do |format|
      format.csv { send_data csv_export_raw_sql(header, @records_array, fields) }
    end
  end

  #Gets all the ready to analyze Charlottesville Gas accounts from the Report module, CvillegasReadyAccount class, paginated
  def cvillegas_ready_accounts
    @c_accounts = Report::CvillegasReadyAccount.paginate(:page => params[:page])
    header = ["Owner Name", "Account Number", "Meter Readings"]
    column_names = Report::CvillegasReadyAccount.column_names
    respond_to do |format|
      format.js
      format.csv { send_data csv_export(header, Report::CvillegasReadyAccount.all, column_names) }
      ajax_respond format, :section_id => "cvillegas_ready_accounts"
    end
  end

  #Gets all the ready to analyze Charlottesville Gas accounts from the Report module, CvillegasReadyAccount class, PRISM formatted
  def cvillegas_ready_accounts_prism
    customers = Report::CvillegasReadyAccount.pluck(:customer_unique_id)
    @records_array = prism_report(customers, "CVILLEGAS")
    header = ["Building ID", "Month", "Day", "Year", "Consumption", "Units", "P-Field", "Group", "Flag"]
    fields = 9 
    respond_to do |format|
      format.csv { send_data csv_export_raw_sql(header, @records_array, fields) }
    end
  end

  #Gets all the ready to analyze Washington Gas accounts from the Report module, WashingtongasReadyAccount class, pagination
  def washingtongas_ready_accounts
    @accounts = Report::WashingtongasReadyAccount.paginate(:page => params[:page])
    header = ["Owner Name", "Account Number", "Meter Readings"]
    column_names = Report::WashingtongasReadyAccount.column_names
    respond_to do |format|
      format.js
      format.csv { send_data csv_export(header, Report::WashingtongasReadyAccount.all, column_names) }
      ajax_respond format, :section_id => "cvillegas_ready_accounts"
    end
  end
 
  #Gets all the ready to analyze Washington Gas accounts from the Report module, WashingtongasReadyAccount class, PRISM formatted
  def washingtongas_ready_accounts_prism
    customers = Report::WashingtongasReadyAccount.pluck(:customer_unique_id)
    @records_array = prism_report(customers, "WASHINGTONGAS")
    header = ["Building ID", "Month", "Day", "Year", "Consumption", "Units", "P-Field", "Group", "Flag"]
    fields = 9 
    respond_to do |format|
      format.csv { send_data csv_export_raw_sql(header, @records_array, fields) }
    end
  end

  private
  #SQL that needs to be run for acquiring all the utility data for given customer unique IDs (aggregated), outputs to PRISM format
  def prism_report(customers, company_name)
    customers = customers.map(&:inspect).join(', ')
    records_array = Array.new
    sql = "SELECT 
			    temp.customer_unique_id,
			    temp.date_month,
			    temp.date_day,
			    temp.date_year,
			    temp.consumption,
			    temp.units,
			    temp.date_PRE_POST,
			    temp.group_field,
			    temp.flag
			FROM
			    (SELECT 
			        temp.customer_unique_id,
			            MONTH(temp.read_date) AS date_month,
			            DAY(temp.read_date) AS date_day,
			            YEAR(temp.read_date) AS date_year,
			            temp.consumption,
			            temp.units,
			            IF(temp.read_date > temp.finish_date, 'POST', 'PRE') AS date_PRE_POST,
			            '' AS 'group_field',
			            'R' AS 'flag',
			            IF(temp.read_date > temp.start_date
			                AND temp.read_date < temp.end_date, 1, NULL) AS gooddata
			    FROM
			        (SELECT 
			        properties.owner_name,
			            properties.id,
			            properties.customer_unique_id,
			            properties.finish_date,
			            record_lookups.company_name,
			            recordings.acctnum,
			            recordings.read_date,
			            recordings.consumption,
			            utility_types.units,
			            IF(EXTRACT(DAY FROM properties.finish_date) < 15, DATE_SUB(DATE_ADD(LAST_DAY(DATE_SUB(properties.finish_date, INTERVAL 1 MONTH)), INTERVAL 15 DAY), INTERVAL 1 YEAR), DATE_ADD(DATE_SUB(DATE_ADD(LAST_DAY(DATE_SUB(properties.finish_date, INTERVAL 1 MONTH)), INTERVAL 15 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH)) AS start_date,
			            IF(EXTRACT(DAY FROM properties.finish_date) < 15, DATE_ADD(DATE_ADD(LAST_DAY(DATE_SUB(properties.finish_date, INTERVAL 1 MONTH)), INTERVAL 15 DAY), INTERVAL 1 YEAR), DATE_ADD(DATE_ADD(DATE_ADD(LAST_DAY(DATE_SUB(properties.finish_date, INTERVAL 1 MONTH)), INTERVAL 15 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH)) AS end_date
			    FROM
			        properties
			    INNER JOIN record_lookups ON record_lookups.property_id = properties.id
			    INNER JOIN recordings ON recordings.acctnum = record_lookups.acct_num
			    LEFT JOIN utility_types ON utility_types.id = recordings.utility_type_id
			    WHERE
			        record_lookups.company_name = '" + company_name + "'
			            AND properties.finish_date IS NOT NULL) temp) temp
			WHERE
			    temp.gooddata IS NOT NULL
			        AND temp.customer_unique_id IN (" + customers + ")
			ORDER BY temp.customer_unique_id ASC , temp.date_year ASC , temp.date_month ASC , temp.date_day ASC;"

   records_array = ActiveRecord::Base.connection.execute(sql)
  end

  #CSV export function that takes in the header, data, and the fields from the ActiveRecord
  def csv_export(header, data, fields)
    CSV.generate do |csv|
      csv << header #["Owner Name", "Customer Unique ID", "Company Name", "Account Number"]
      data.each do |record|
        csv << record.attributes.values_at(*fields)
      end
    end
  end
  
  #CSV export function that takes in the header, data, fields for raw SQL output
  def csv_export_raw_sql(header, data, fields)
    CSV.generate do |csv|
      csv << header #["Owner Name", "Customer Unique ID", "Company Name", "Account Number"]
      recordline = Array.new(fields)
      data.each do |record|
        fields.times{ |i| recordline[i] = record[i]}
        csv << recordline #[record[0], record[2], record[3], record[4]]
        recordline = Array.new(fields)
      end
    end
  end


end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/views/analysis/_cvillegas_ready_accounts.html.erb
<table class="table table-striped table-bordered">
  <%= ajax_links :section_id => "links2" do %>
    <%= will_paginate @c_accounts, renderer: BootstrapPagination::Rails %>
  <% end %>

  <tr>
    <th>Owner Name</th>
    <th>Account Number</th>
    <th>Meter Readings</th>
  </tr>
  <%= ajax_loadzone do %>
  <% @c_accounts.each do |account| %>
    <tr>
      <td><%= link_to account.owner_name, 'dashboard/property_report?customer_unique_id=' + account.customer_unique_id %></td>
      <td><%= account.acctnum %></td>
      <td><%= account.acceptedDatapoints %></td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/analysis/_dominion_ready.html.erb
<table class="table table-striped" border="1">
  <%= ajax_links :section_id => "page" do %>
    <%= will_paginate @accounts %>
  <% end %>

  <tr>
    <th>Owner Name</th>
    <th>Account Number</th>
    <th>Meter Readings</th>
  </tr>
  <%= ajax_loadzone do %>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= link_to account.owner_name, 'dashboard/property_report?owner=' + account.owner_name %></td>
      <td><%= account.acctnum %></td>
      <td><%= account.acceptedDatapoints %></td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/analysis/_dominion_ready_accounts.html.erb
<table class="table table-striped table-bordered">
  <%= ajax_links :section_id => "links" do %>
    <%= will_paginate @accounts, renderer: BootstrapPagination::Rails %>
  <% end %>

  <tr>
    <th>Owner Name</th>
    <th>Account Number</th>
    <th>Meter Readings</th>
  </tr>
  <%= ajax_loadzone do %>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= link_to account.owner_name, 'dashboard/property_report?customer_unique_id=' + account.customer_unique_id %></td>
      <td><%= account.acctnum %></td>
      <td><%= account.acceptedDatapoints %></td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/analysis/_null_accounts.html.erb
<table class="table table-striped table-bordered">
  <%= ajax_links :section_id => "links3" do %>
    <%= will_paginate @n_accounts, renderer: BootstrapPagination::Rails %>
    </ul>
  <% end %>

  <tr>
    <th>Owner Name</th>
    <th>Customer Unique ID</th>
    <th>Company Name</th>
    <th>Account Number</th>
  </tr>
  <%= ajax_loadzone do %>
  <% @n_accounts.each do |account| %>
    <tr>
      <td><%= link_to account.owner_name, 'dashboard/property_report?customer_unique_id=' + account.customer_unique_id %></td>
      <td><%= account.customer_unique_id %></td>
      <td><%= account.company_name %></td>
      <td><%= account.acct_num %></td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/analysis/_report_null_account.html.erb
<table class="table table-striped" border="1">
  <tr>
    <th>Owner Name</th>
    <th>Customer Unique ID</th>
    <th>Company Name</th>
    <th>Account Number</th>
  </tr>

<% @records_array.each do |record| %>
  <tr>
    <td><%= link_to owner_name, 'dashboard/property_report?customer_unique_id=' + customer_unique_id %></td>
    <td><%= customer_unique_id %></td>
    <td><%= company_name %></td>
    <td><%= acct_num %></td>
  </tr>
<% end %>
</table>

app/views/analysis/_washingtongas_ready_accounts.html.erb
<table class="table table-striped table-bordered">
  <%= ajax_links :section_id => "links2" do %>
    <%= will_paginate @accounts, renderer: BootstrapPagination::Rails %>
  <% end %>

  <tr>
    <th>Owner Name</th>
    <th>Account Number</th>
    <th>Meter Readings</th>
  </tr>
  <%= ajax_loadzone do %>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= link_to account.owner_name, 'dashboard/property_report?customer_unique_id=' + account.customer_unique_id %></td>
      <td><%= account.acctnum %></td>
      <td><%= account.acceptedDatapoints %></td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/analysis/cvillegas_ready_accounts.js.erb
$('#cvillegas_rdy').html("<%= escape_javascript(ajax_section :id => "cvillegas_ready_accounts", :render => "cvillegas_ready_accounts") %>");
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});  

app/views/analysis/dominion_ready.js.erb
$('#dominion_rdy').html("<%= escape_javascript(ajax_section :id => "dominion_ready", :render => "dominion_ready") %>");
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});  

app/views/analysis/dominion_ready_accounts.js.erb
$('#dominion_rdy').html("<%= escape_javascript(ajax_section :id => "dominion_ready_accounts", :render => "dominion_ready_accounts") %>");
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});  

app/views/analysis/index.html.erb
<style type="text/css">
	a:hover {color: #888;}
</style>
<div class="container marketing">
	<h1>Analysis</h1>
	<ul class="nav nav-tabs">
	 	<li class="active"><a href="#Dominion" data-toggle="tab">Dominion Virginia Power</a></li>
	  	<li><a href="#CvilleGas" data-toggle="tab">Charlottesville Gas</a></li>
	  	<li><a href="#WashingtonGas" data-toggle="tab">Washington Gas</a></li>
	  	<li><a href="#NullAccts" data-toggle="tab">Null Accounts</a></li>
	</ul>
	<script>
	$('#myTab a[href="#CvilleGas"]').click(function (e) {
	  	e.preventDefault()
	  	$(this).tab('show')
	})
	$('#myTab a[href="#WashingtonGas"]').click(function (e) {
	  	e.preventDefault()
	  	$(this).tab('show')
	})
	$('#myTab a[href="#NullAccts"]').click(function (e) {
	  	e.preventDefault()
	  	$(this).tab('show')
	})
	</script>
	<div class="tab-content">
		<div class="tab-pane active" id="Dominion">
			<div class="row">
				<div class="col-lg-6">
					<h4>Ready to Analyze Dominion Virginia Power Customers</h4>
				</div>
				<div class="col-lg-2">
					<%= button_to "Generate HTML View", analysis_dominion_ready_accounts_path, :remote => true, :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to CSV", analysis_dominion_ready_accounts_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to PRISM Format", analysis_dominion_ready_accounts_prism_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
			</div>
                        <br/>
			<div id="dominion_rdy"></div>
			</br>
		</div>

		<div class="tab-pane" id="CvilleGas" href="#CvilleGas">
			<div class="row">
				<div class="col-lg-6">
					<h4>Ready to Analyze Charlottesville Gas Customers</h4>
				</div>
				<div class="col-lg-2">
					<%= button_to "Generate HTML View", analysis_cvillegas_ready_accounts_path, :remote => true, :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to CSV", analysis_cvillegas_ready_accounts_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to PRISM Format", analysis_cvillegas_ready_accounts_prism_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
			</div>
                        <br/>
			<div id="cvillegas_rdy"></div>
			</br>	
		</div>

		<div class="tab-pane" id="WashingtonGas" href="#WashingtonGas">
			<div class="row">
				<div class="col-lg-6">
					<h4>Ready to Analyze Washington Gas Customers</h4>
				</div>

				<div class="col-lg-2">
					<%= button_to "Generate HTML View", analysis_washingtongas_ready_accounts_path, :remote => true, :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to CSV", analysis_washingtongas_ready_accounts_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-2">
					<%= button_to "Export to PRISM Format", analysis_washingtongas_ready_accounts_prism_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
			</div>
			<br/>
                        <div id="washingtongas_rdy"></div>
			</br>
		</div>
		<div class="tab-pane" id="NullAccts" href="#NullAccts">
			<div class="row">
				<div class="col-lg-6">
					<h4>Null Accounts</h4>
				</div>
				<div class="col-lg-3">
					<%= button_to "Generate HTML View", analysis_null_accounts_path, :remote => true, :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
				<div class="col-lg-3">
					<%= button_to "Export to CSV", analysis_null_accounts_path(:format => "csv"), :method => "get", type: 'button', class: 'btn btn-primary center-block', style: 'margin-top:5px; margin-bottom:10px;' %>
				</div>
			</div>
                        <br/>
			<div id="null_accts"></div>
			<%# ajax_section :id => "null_accounts", :render => "null_accounts" %>
			</br>
		</div>
	</div>
</div>

app/views/analysis/index.js.erb
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});

app/views/analysis/null_accounts.js.erb
$('#null_accts').html("<%= escape_javascript(ajax_section :id => "null_accounts", :render => "null_accounts") %>");
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});  

app/views/analysis/washingtongas_ready_accounts.js.erb
$('#washingtongas_rdy').html("<%= escape_javascript(ajax_section :id => "washingtongas_ready_accounts", :render => "washingtongas_ready_accounts") %>");
$(function () {  
  $('.pagination a').on("click", function () {  
    $.get(this.href, null, null, 'script');  
    return false;  
  });  
});  