config/routes.rb
Public::Application.routes.draw do

  resources :propertymeasures
  resources :installed_measure_types
  resources :record_lookups
  
  devise_for :users, :controllers => {:registrations => "newusers", :destroy => "newusers"}
  devise_scope :user do
  authenticated :user do
       root :to =>'dashboard#index'
	end
    unauthenticated :user do
	root :to => 'devise/sessions#new'
   end
  end

  resources :recordings
  resources :properties

  resources :newusers
  resources :users

  get "dashboard/property_report"

  get "dashboard/prism_report_electric"
  get "dashboard/prism_report_gas"
  post '/uploads/upload' => 'uploads#upload'
  post '/uploads/uploadGas' => 'uploads#uploadGas'
  resources :dashboard

  
  
  post '/stagings/insert' => 'stagings#insert'
  post '/stagings/destroyAll' => 'stagings#destroyAll'
  resources :stagings do
	collection do
    		put :update_attribute_on_the_spot
    		get :get_attribute_on_the_spot
  	end
  end

  get 'analysis', to: 'analysis#index'
  get 'analysis/null_accounts'
  get 'analysis/dominion_ready_accounts'
  get 'analysis/dominion_ready_accounts_prism'
  get 'analysis/cvillegas_ready_accounts'
  get 'analysis/cvillegas_ready_accounts_prism'
  get 'analysis/washingtongas_ready_accounts'
  get 'analysis/washingtongas_ready_accounts_prism'

  get 'filtering', to: 'filtering#index'
  match '/filtering_reset' => 'filtering#reset', :as=>'reset'
  get "filtering/prism_report_electric", :defaults=> {format: 'csv'}
  get "filtering/prism_report_gas", :defaults=> {format: 'csv'}

  get 'requests', to: 'requests#index'
  get 'requests/dominion_request_accounts'
  get 'requests/cvillegas_request_accounts'
  get 'requests/washingtongas_request_accounts'

  get 'uploads/stagings', to: 'stagings#index'
  resources :uploads do
	member do
	    get :process
	end
  end

  root :to => "dashboard#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :file_name, :process_date, :status, :status, :upload_date, :uploaded_by
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json 

  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render json: @upload, status: :created, location: @upload }
	
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end
  #		#electricity = 1 gas = 2
  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
	if File.exists?(Rails.root.join('..', 'uploads', @upload.file_name))
		File.delete(Rails.root.join('..', 'uploads', @upload.file_name))	
	end
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
  #Main function of this page
  #Uploaded_io = the file information
  #Uploaded_io is used to access further information on the file
  #Status = Success of upload
  #There are two upload functions that are slightly different. This is done to handle the two different forms of input, Gas, and Electric, since there is nothing in the files to indicate which is which.
  #Currently both function identically besides uploadGas indicating a 2 to the convert_to_stagings Methods.
  def upload
        uploaded_io = params[:file]
        railspath =  Rails.root.join('..', 'uploads')
        path = railspath.to_s
        filename = uploaded_io.original_filename

	#Goes to the generic upload_file portion of the code, handles the actual file uploading
	status = upload_file filename, path, uploaded_io
        

	#Checks if the file uploaded properly and then handles them appropiately based on the file type. Processing unfortunately currently indicates that the file has attempted to process. If for some reason the file stops processing, it will remain in the processing status.
        if status != "Duplicate file found in uploads, file not uploaded" && status != "File not uploaded properly"
		flash[:notice] = status
		Thread.new do		
			if uploaded_io.content_type == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsXLSX path, uploaded_io, 1
			elsif uploaded_io.content_type == 'application/vnd.ms-excel'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsXLS path, uploaded_io, 1
			elsif uploaded_io.content_type == 'text/csv'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsCSV path, uploaded_io, 1 
			end
		end	
	else flash[:alert] = status end

	redirect_to :action => 'index'	
  end
  #This method functions identical to the previous upload function but replaces 1 with 2 to indicate Gas to the conversion methods
  def uploadGas
        uploaded_io = params[:file]
        railspath =  Rails.root.join('..', 'uploads')
        path = railspath.to_s
        filename = uploaded_io.original_filename

	status = upload_file filename, path, uploaded_io
        

        if status != "Duplicate file found in uploads, file not uploaded" && status != "File not uploaded properly"
		flash[:notice] = status
		Thread.new do
			if uploaded_io.content_type == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsXLSX path, uploaded_io, 2
			elsif uploaded_io.content_type == 'application/vnd.ms-excel'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsXLS path, uploaded_io, 2
			elsif uploaded_io.content_type == 'text/csv'
				Upload.update_all( {:status => 'Processing'}, {:file_name => uploaded_io.original_filename})
				convert_to_stagingsCSV path, uploaded_io, 2 
			end
		end	
	else flash[:alert] = status end
	
	redirect_to :action => 'index'	
  end            

#handles actual file upload, creates the file and places it in an upload directory. Will fail if no upload directory exists. This needs to be in level above where your application is running. 
  def upload_file(filename, path, uploaded_io)
	status = "File not uploaded properly"	
	if !File.exists?(path + "//" + filename) && File.directory?(path)
            File.open(path + "//" + filename, 'w') do |file|
                input = uploaded_io.read
                input.force_encoding('UTF-8')
                file.write(input)
            end
            Upload.create(:file_name => uploaded_io.original_filename, :status => 'Not Processed', :upload_date => Time.now)
            upload_record = Upload.find_by_file_name(uploaded_io.original_filename)
            upload_record.uploaded_by = current_user.email
            upload_record.save
	    status = "File has been uploaded successfully, check the uploaded files to see its processing status."
	elsif File.exists?(path + "//" + filename)
	status = "Duplicate file found in uploads, file not uploaded" 
	end
	status
  end
  #PRocesses the xlsx file, looking for headers in the xlsx file named AccountNum, DateRead, Consumption, and DaysUsed. Order and additional columns do not matter as long as these match. Uses the gem roo's excelx class to handle reading the file.
  def convert_to_stagingsXLSX(path, uploaded_io, type)
	fields_to_insert = %w{ AccountNum DateRead Consumption DaysUsed }
	rows_to_insert = []

	Dir[path+"/" + uploaded_io.original_filename].each do |file|
		    #handles the first sheet and first sheet only
                    file_path = "#{file}"
                    file_basename = File.basename(file, ".xlsx")
                    xlsx = Roo::Excelx.new(file_path.to_s)
                    $i = xlsx.sheets.length - 1
		    xlsx.default_sheet = xlsx.sheets[0]
		    headers = Hash.new
		    xlsx.row(1).each_with_index {|header,i|
		    headers[header] = i
	            }

 
		    #Looks at each row and extracts the data
                    ((xlsx.first_row + 1)..xlsx.last_row).each do |row|
			    
		            acctnum = xlsx.row(row)[headers['AccountNum']]
		            date = xlsx.row(row)[headers['DateRead']]
			    amt_kwh = xlsx.row(row)[headers['Consumption']]
			    days_used = xlsx.row(row)[headers['DaysUsed']]
		            
			    #Handles excelx formate Dates
			    #date = DateTime.new(1899,12,30) + Integer(date).days 
			    #Creates a staging IF staging does not already exist AND IF recording with same date and acct num does not exist in the Database
 			    if !Recording.exists?(:acctnum => acctnum.to_i, :read_date=>date)
			    	Staging.where({"acctnum"=>acctnum.to_i, "consumption"=>amt_kwh, "days_in_month"=>days_used, "read_date"=>date, "utility_type_id" => type}).first_or_create(:locked => false)
			    end
                    end
		   
		    
                    Upload.update_all( {:status => 'Processed', :process_date => Time.now}, {:file_name => uploaded_io.original_filename})

        end

  end
#Functions virtually simular to XLSX but uses Roos Excel class instead. All xlsx and excelx instances replaced with xls and excel. Needs to handle date differently for XLS files than XLSX. 
	def convert_to_stagingsXLS(path, uploaded_io, type)
		fields_to_insert = %w{ AccountNum DateRead Consumption DaysUsed }
		rows_to_insert = []
		Dir[path+"/" + uploaded_io.original_filename].each do |file|
		            file_path = "#{file}"
		            file_basename = File.basename(file, ".xls")
		            xls = Roo::Excel.new(file_path.to_s)
		            $i = xls.sheets.length - 1
			    xls.default_sheet = xls.sheets[0]
			    headers = Hash.new
			    xls.row(1).each_with_index {|header,i|
			    headers[header] = i
			    }
	 

		            ((xls.first_row + 1)..xls.last_row).each do |row|

				    acctnum = xls.row(row)[headers['AccountNum']]
				    date = xls.row(row)[headers['DateRead']]
				    amt_kwh = xls.row(row)[headers['Consumption']]
				    days_used = xls.row(row)[headers['DaysUsed']]
				    
				    #Needs to handle date differently for XLS files than XLSX. 
				    #date = DateTime.new(1899,12,30) + Integer(date).days
				if !Recording.exists?(:acctnum => acctnum.to_i, :read_date=>date)  
				    Staging.where({"acctnum"=>acctnum.to_i, "consumption"=>amt_kwh, "days_in_month"=>days_used, "read_date"=>date, "utility_type_id" => type}).first_or_create(:locked => false)
				end
		            end

		            Upload.update_all( {:status => 'Processed', :process_date => Time.now}, {:file_name => uploaded_io.original_filename})

		end

	  end

app/helpers/uploads_helper.rb
module UploadsHelper
require 'iconv'
require 'roo'

	# change excel files to csv
	def xls2csv
	    print "start conversion....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	    Dir["/leap/public/uploads/*.xlsx"].each do |file|  
	      file_path = "#{file}"
	      file_basename = File.basename(file, ".xlsx")
	      xlsx = Roo::Excelx.new(file_path)
	      $i = xlsx.sheets.length - 1
	      while $i >= 0 do
		xlsx.default_sheet = xlsx.sheets[$i]
		xlsx.to_csv("/leap/public/uploads/#{file_basename}#{$i}.csv")
		$i -=1	
	      end
	      FileUtils.remove(file)
	      print "Converted file #{file} \n"
	    end
	end
end

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :upload_date %><br />
    <%= f.datetime_select :upload_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :process_date %><br />
    <%= f.datetime_select :process_date %>
  </div>
  <div class="field">
    <%= f.label :uploaded_by %><br />
    <%= f.text_field :uploaded_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div class= "container">
<h1>Upload</h1>

<!--<h3>Processed Data</h3>-->
<%= button_to "Processed Data", stagings_path, :method => "get", type: 'button', class: "btn btn-primary btn-sm", data: { toggle:"tooltip", placement:"right"}, title: "Click here to see any data currently uploaded using this page. You will be able to modify it before confirming that it is correct."%>

<h3>Upload Data Format</h3>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>AccountNum</th>
      <th>DateRead</th>
      <th>Consumption</th>
      <th>DaysUsed</th>
    </tr>
  </thead>
  <tr>
    <td> </td>
    <td> </td>
    <td> </td>
    <td> </td>
  </tr>

</table>

<h3>Upload for Electric Data</h3>
		<%= form_tag({:action => :upload,  :controller=>"uploads"}, :multipart => true) do %>
		  <%= file_field_tag 'file' %>
		<br>
		<%= submit_tag( "Upload Electric Data", class: 'btn btn-primary btn-sm') %>
		<br>
		<% end %>
		
    <br>
<h3>Upload for Gas Data</h3>
		<%= form_tag({:action => :uploadGas,  :controller=>"uploads"}, :multipart => true) do %>
		  <%= file_field_tag 'file' %>
		<br>
		<%= submit_tag( "Upload Gas Data", class: 'btn btn-primary btn-sm') %>
		<br>
		<% end %>

		<div id="ajax">
		<!--% render :partial => "report" %-->
		</div>


<h3>Current Uploaded Files</h3>

<table class="table table-striped">
  <tr>
    <th>File Name</th>
    <th>Status</th>
    <th>Upload Date</th>
    <th>Process Date</th>
    <th>Uploaded by</th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.file_name %></td>
    <td><%= upload.status %></td>
    <td><%= upload.upload_date %></td>
    <td><%= upload.process_date %></td>
    <td><%= upload.uploaded_by %></td>
    <td><%#link_to 'Process', process_uploads_path(upload, method: :get), data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
</div>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File name:</b>
  <%= @upload.file_name %>
</p>

<p>
  <b>Status:</b>
  <%= @upload.status %>
</p>

<p>
  <b>Upload date:</b>
  <%= @upload.upload_date %>
</p>

<p>
  <b>Status:</b>
  <%= @upload.status %>
</p>

<p>
  <b>Process date:</b>
  <%= @upload.process_date %>
</p>

<p>
  <b>Uploaded by:</b>
  <%= @upload.uploaded_by %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>